require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AttrsController do

  # This should return the minimal set of attributes required to create a valid
  # Attr. As you add validations to Attr, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AttrsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all attrs as @attrs" do
      attr = Attr.create! valid_attributes
      get :index, {}, valid_session
      assigns(:attrs).should eq([attr])
    end
  end

  describe "GET show" do
    it "assigns the requested attr as @attr" do
      attr = Attr.create! valid_attributes
      get :show, {:id => attr.to_param}, valid_session
      assigns(:attr).should eq(attr)
    end
  end

  describe "GET new" do
    it "assigns a new attr as @attr" do
      get :new, {}, valid_session
      assigns(:attr).should be_a_new(Attr)
    end
  end

  describe "GET edit" do
    it "assigns the requested attr as @attr" do
      attr = Attr.create! valid_attributes
      get :edit, {:id => attr.to_param}, valid_session
      assigns(:attr).should eq(attr)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Attr" do
        expect {
          post :create, {:attr => valid_attributes}, valid_session
        }.to change(Attr, :count).by(1)
      end

      it "assigns a newly created attr as @attr" do
        post :create, {:attr => valid_attributes}, valid_session
        assigns(:attr).should be_a(Attr)
        assigns(:attr).should be_persisted
      end

      it "redirects to the created attr" do
        post :create, {:attr => valid_attributes}, valid_session
        response.should redirect_to(Attr.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved attr as @attr" do
        # Trigger the behavior that occurs when invalid params are submitted
        Attr.any_instance.stub(:save).and_return(false)
        post :create, {:attr => { "name" => "invalid value" }}, valid_session
        assigns(:attr).should be_a_new(Attr)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Attr.any_instance.stub(:save).and_return(false)
        post :create, {:attr => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested attr" do
        attr = Attr.create! valid_attributes
        # Assuming there are no other attrs in the database, this
        # specifies that the Attr created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Attr.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => attr.to_param, :attr => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested attr as @attr" do
        attr = Attr.create! valid_attributes
        put :update, {:id => attr.to_param, :attr => valid_attributes}, valid_session
        assigns(:attr).should eq(attr)
      end

      it "redirects to the attr" do
        attr = Attr.create! valid_attributes
        put :update, {:id => attr.to_param, :attr => valid_attributes}, valid_session
        response.should redirect_to(attr)
      end
    end

    describe "with invalid params" do
      it "assigns the attr as @attr" do
        attr = Attr.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Attr.any_instance.stub(:save).and_return(false)
        put :update, {:id => attr.to_param, :attr => { "name" => "invalid value" }}, valid_session
        assigns(:attr).should eq(attr)
      end

      it "re-renders the 'edit' template" do
        attr = Attr.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Attr.any_instance.stub(:save).and_return(false)
        put :update, {:id => attr.to_param, :attr => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested attr" do
      attr = Attr.create! valid_attributes
      expect {
        delete :destroy, {:id => attr.to_param}, valid_session
      }.to change(Attr, :count).by(-1)
    end

    it "redirects to the attrs list" do
      attr = Attr.create! valid_attributes
      delete :destroy, {:id => attr.to_param}, valid_session
      response.should redirect_to(attrs_url)
    end
  end

end
